baseURL = 'https://winkkyfarms.com/'
languageCode = 'en-us'
title = 'Winkky Farms'
theme = 'winkky-farm'

[params]
  subtitle = "Where Family, Land, and Tradition Meet"
  author = "The Winkky Family"
  description = "Three generations of farming wisdom, seasonal stories from the fields, and the simple joys of life lived close to the land. Welcome to our corner of the world."
  featured_image = "/images/placeholder.svg"
  background_color_class = "bg-washed-green"
  
[menu]
  [[menu.main]]
    name = "The Fields"
    url = "/categories/crops/"
    weight = 1
  [[menu.main]]
    name = "The Animals"
    url = "/categories/livestock/"
    weight = 2
  [[menu.main]]
    name = "Seasons"
    url = "/categories/seasons/"
    weight = 3
  [[menu.main]]
    name = "Farm Stories"
    url = "/categories/farm-life/"
    weight = 4
  [[menu.main]]
    name = "Our Roots"
    url = "/categories/history/"
    weight = 5
  [[menu.main]]
    name = "The Family"
    url = "/about/"
    weight = 6
